name: Deploy
on:
  push:
    branches: main

defaults:
  run:
    shell: bash

jobs:
  cibuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: apt install -y leiningen make
      - run: make
