name: Deploy
on:
  push:
    branches: main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

defaults:
  run:
    shell: bash

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  ci-build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install-system-deps
        run: sudo apt install -y curl make rlwrap clojure
      - name: download-newer-clojure
        run: curl -L -O https://github.com/clojure/brew-install/releases/latest/download/posix-install.sh
      - name: chmod-posix-install
        run: chmod +x posix-install.sh
      - name: install-newer-clojure
        run: sudo ./posix-install.sh
      - name: make
        run: make
      - name: upload
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'choices/resources/public'
      - name: deploy-gh-pages
        id: deployment
        uses: actions/deploy-pages@v1
